title: "My Project"
project_dir: "./"
sections:
  - section:
    title: "Section 1"
    commands:
      - command:
        title: "List NPM Modules"
        action: "npm ls"
      - command:
        title: "Test"
        action: "npm test"

